#!/bin/bash
datafile='../q.txt'

function one_round {

    while read -r line;
        do
            IFS=' ' read -r -a array <<< "$line"
            url="${array[0]}"
            postfix="${array[1]}"
            filename=~/Downloads/`echo -n "$url" | openssl sha1`.sha1.$postfix
            if [ -f "$filename" ]
            then
                echo "[exist]$filename."
                continue;
            fi
			echo "proxychains4 wget --no-check-certificate --tries=3 -c -T 3 -O $filename $url &"
            proxychains4 wget --no-check-certificate --tries=3 -c -T 3 -O $filename $url &
            echo '****** '$?
            echo '--------------------------'
            
        done < $1
    rm -f $1
}

one_round $datafile

function run {
    while :
        do
            sleep 1
            if [ ! -f $datafile ]; then
                # echo "no source to download"
                continue;
            fi
            one_round $1
        done
}

run $datafile
